# Generated by Django 3.1.4 on 2020-12-29 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=300)),
                ('tweet_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 29, 17, 35, 44, 361189, tzinfo=utc))),
                ('tweet_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmali', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('userPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userpost', models.CharField(max_length=300)),
                ('whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.users')),
            ],
        ),
    ]
