# Generated by Django 3.1.4 on 2020-12-17 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=300)),
                ('comment_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 17, 18, 34, 2, 40604, tzinfo=utc))),
                ('comment_id', models.IntegerField(default=0, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=300)),
                ('tweet_date', models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 17, 18, 34, 2, 39607, tzinfo=utc))),
                ('tweet_id', models.IntegerField(default=0, max_length=15)),
            ],
        ),
    ]
