# Generated by Django 3.1.4 on 2020-12-19 10:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20201217_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmali', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('userPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 19, 10, 25, 37, 992675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 19, 10, 25, 37, 992675, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(default=0),
        ),
    ]
