# Generated by Django 3.1.4 on 2020-12-28 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20201224_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 28, 16, 30, 10, 25056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 28, 16, 30, 10, 25056, tzinfo=utc)),
        ),
    ]
