# Generated by Django 3.1.4 on 2020-12-29 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20201229_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 29, 18, 13, 13, 112672, tzinfo=utc)),
        ),
    ]
