# Generated by Django 3.1.4 on 2020-12-29 18:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_auto_20201229_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 29, 18, 22, 50, 858499, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='post1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_post', models.CharField(max_length=250)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.users')),
            ],
        ),
    ]
