# Generated by Django 3.1.4 on 2020-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_auto_20201229_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_date',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=50),
        ),
    ]
