# Generated by Django 3.1.4 on 2020-12-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_auto_20201229_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='comm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.CharField(max_length=250)),
                ('comm_id', models.CharField(max_length=50)),
            ],
        ),
    ]
