# Generated by Django 3.1.4 on 2020-12-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='whom',
        ),
        migrations.RemoveField(
            model_name='post1',
            name='us',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='post1',
        ),
    ]
