# Generated by Django 3.1.4 on 2020-12-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0016_auto_20201230_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
